# Start with the default.yaml file, which we will modify below
template: config/default.yaml

image.wcs.max_sun_angle: 50
image.wcs.force_cvz: true

input.obseq_data.file_name: RomanTDS/Roman_TDS_obseq_11_6_23.fits

output.dir: 'output/tds'  # Adjust this to a shared location with sufficient storage
output.file_name.format: "Roman_TDS_truth_%s_%i_%i.fits.gz"
output.truth.dir: 'output/tds'  # Adjust this to a shared location with sufficient storage
output.truth.file_name.format: "Roman_TDS_index_%s_%i_%i.txt"
