# Start with the default.yaml file, which we will modify below
template: default.yaml

# Update the run-specific fields
# Or you can update the entire field if more convenient
input.obseq_data.file_name: /lus/grand/projects/RomanDESC/final_roman_runfiles/tds/Roman_TDS_obseq_11_6_23.fits
input.sky_catalog.file_name: /lus/grand/projects/RomanDESC/roman_rubin_cats_v1.1.2_faint/skyCatalog.yaml 
input.sky_catalog.obj_types: ['diffsky_galaxy', 'star', 'snana']

output.dir: /lus/grand/projects/RomanDESC/roman_output/RomanTDS/images/truth
output.file_name.format: "Roman_TDS_truth_%s_%i_%i.fits.gz"
output.truth.dir: /lus/grand/projects/RomanDESC/roman_output/RomanTDS/truth
output.truth.file_name.format: "Roman_TDS_index_%s_%i_%i.txt"
