# Start with the default.yaml file, which we will modify below
template: default.yaml

# Update the run-specific fields
# Or you can update the entire field if more convenient
image.random_seed:
    - { type: ObSeqData, field: visit }
image.ignore_noise: False
image.stray_light: True
image.thermal_background: True
image.reciprocity_failure: True
image.dark_current: True
image.nonlinearity: True
image.ipc: True
image.read_noise: True
image.nobjects: null

input.obseq_data.file_name: /hpc/group/cosmology/OpenUniverse2024/RomanWAS/Roman_WAS_obseq_11_1_23.fits
input.obseq_data.visit: 1
input.roman_psf.n_waves: 5
input.sky_catalog.file_name: /hpc/home/yf194/Work/projects/roman_imsim/config/skyCatalog.yaml
input.sky_catalog.obj_types: ['diffsky_galaxy','star','snana']

output.dir: /hpc/group/cosmology/yuedong/roman_output/RomanWAS/images/truth
output.file_name.format: "Roman_WAS_truth_%s_%i_%i.fits.gz"
output.truth.dir: /hpc/group/cosmology/yuedong/roman_output/RomanWAS/truth
output.truth.file_name.format: "Roman_WAS_index_%s_%i_%i.txt"
output.truth.columns.mag: "@mag"
output.truth.columns.obj_type: "@object_type"
